# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20170228_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='description',
            new_name='block_description',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='name',
            new_name='block_name',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='status',
            new_name='block_status',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='manager',
            new_name='manager_name',
        ),
    ]
