# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170228_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_timestamp',
        ),
    ]
