# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_create_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
