# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_create_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='status',
            new_name='article_status',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
    ]
